services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=maria
      - MYSQL_DATABASE=maria
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=maria
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    restart: always

  wordpress:
    build: .
    image: wordpress:latest
    env_file: ./.env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html/wp-content/plugins/botspot
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always

volumes:
  wordpress: