networks:
  proxy-network:
    external: true
  wordpress-network:
    driver: bridge
    
volumes:
  wordpress:

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    restart: always
    networks:
      - proxy-network
      - wordpress-network

  botspot_wordpress:
    container_name: botspot_wordpress
    build: .
    image: wordpress:latest
    env_file: ./.env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    ports:
      - 8080:80
    volumes:
      - ./wordpress:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/botspot
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./botspot-button:/var/www/html/wp-content/plugins/botspot-button
    restart: always
    networks:
      - proxy-network
      - wordpress-network